# AFDM

 - Author:  Ricardo Vallejo R.

# 1. téléchargez le contenu de la base de données et affichez son contenue

In [86]:
import pandas as pd
import matplotlib.pyplot as plt
import statistics
import numpy as np
import scipy.stats
import seaborn as sns

dataOriginal = pd.read_excel("Autos_Mixtes.xlsx")
pd.set_option('display.max_rows', None)
n_data = dataOriginal.shape[0]

dataOriginal

Modele  puissance  longueur  hauteur  poids  CO2 origine carburant  \
0  GOLF                 75       421      149   1217  143  Europe    Diesel   
1  CITRONC4            138       426      146   1381  142  France    Diesel   
2  P607                204       491      145   1723  223  France    Diesel   
3  VELSATIS            150       486      158   1735  188  France    Diesel   
4  CITRONC2             61       367      147    932  141  France   Essence   
5  CHRYS300            340       502      148   1835  291  Autres   Essence   
6  AUDIA3              102       421      143   1205  168  Europe   Essence   
7  OUTLAND             202       455      167   1595  237  Autres    Diesel   
8  PTCRUISER           223       429      154   1595  235  Autres   Essence   
9  SANTA_FE            125       450      173   1757  197  Autres    Diesel   

   4X4  
0  non  
1  non  
2  non  
3  non  
4  non  
5  non  
6  non  
7  oui  
8  non  
9  oui

# 2. Identifiez les données quantitatives et les données qualitatives

In [87]:
v_qualitative = ['origine', 'carburant', '4X4']
v_quantitative = ['puissance', 'longueur', 'hauteur', 'poids', 'CO2']

# 3. Effectuez la préparation des données quantitatives en vue d’une analyse factorielle

# Variables Quantitatives

In [88]:

Z1 = dataOriginal[v_quantitative]

In [89]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(Z1)
Z1_std = scaler.transform(Z1)
Z1_standarized = pd.DataFrame(Z1_std)
Z1_standarized = pd.DataFrame(Z1_std, columns=Z1.columns)
Z1_standarized.round(3)

puissance  longueur  hauteur  poids    CO2
0     -1.103    -0.614   -0.419 -0.989 -1.127
1     -0.304    -0.485   -0.733 -0.411 -1.148
2      0.532     1.192   -0.838  0.795  0.558
3     -0.152     1.063    0.524  0.837 -0.179
4     -1.280    -2.007   -0.628 -1.993 -1.169
5      2.256     1.476   -0.524  1.189  1.990
6     -0.761    -0.614   -1.047 -1.031 -0.600
7      0.507     0.263    1.466  0.344  0.853
8      0.773    -0.408    0.105  0.344  0.811
9     -0.469     0.134    2.094  0.915  0.011

In [90]:
Z1_standarized.describe().round(3)

puissance  longueur  hauteur   poids     CO2
count     10.000    10.000   10.000  10.000  10.000
mean      -0.000    -0.000   -0.000   0.000  -0.000
std        1.054     1.054    1.054   1.054   1.054
min       -1.280    -2.007   -1.047  -1.993  -1.169
25%       -0.688    -0.582   -0.707  -0.844  -0.995
50%       -0.228    -0.137   -0.471   0.344  -0.084
75%        0.526     0.863    0.419   0.826   0.748
max        2.256     1.476    2.094   1.189   1.990

# Variables Qualitatives

4. Représentez les données qualitatives sous la forme d’un tableau disjonctif (TDC) en vue d’une analyse factorielle.

In [91]:
dataX = dataOriginal[v_qualitative]
K_disj = pd.get_dummies(dataX,prefix='',prefix_sep='')

In [92]:
K_disj

Autres  Europe  France  Diesel  Essence  non  oui
0       0       1       0       1        0    1    0
1       0       0       1       1        0    1    0
2       0       0       1       1        0    1    0
3       0       0       1       1        0    1    0
4       0       0       1       0        1    1    0
5       1       0       0       0        1    1    0
6       0       1       0       0        1    1    0
7       1       0       0       1        0    0    1
8       1       0       0       0        1    1    0
9       1       0       0       1        0    0    1

In [93]:
columnsx=K_disj.columns
columnsx

Index(['Autres', 'Europe', 'France', 'Diesel', 'Essence', 'non', 'oui'], dtype='object')

In [94]:
Nj = K_disj[columnsx].sum()
Nj.to_frame()

0
Autres   4
Europe   2
France   4
Diesel   6
Essence  4
non      8
oui      2

In [95]:
N = dataOriginal.shape[0]
N

10

In [96]:
Pj = Nj / N
Pj.to_frame()

0
Autres   0.4
Europe   0.2
France   0.4
Diesel   0.6
Essence  0.4
non      0.8
oui      0.2

# Normalisation variables qualitatives

5. Représentez une matrice sommaire des données

In [97]:
import math 

Z2 = pd.DataFrame(columns=K_disj.columns) 
for col in K_disj.columns:
    Z2[col] = K_disj[col] / math.sqrt(Pj[col])
Z2

Autres    Europe    France    Diesel   Essence       non       oui
0  0.000000  2.236068  0.000000  1.290994  0.000000  1.118034  0.000000
1  0.000000  0.000000  1.581139  1.290994  0.000000  1.118034  0.000000
2  0.000000  0.000000  1.581139  1.290994  0.000000  1.118034  0.000000
3  0.000000  0.000000  1.581139  1.290994  0.000000  1.118034  0.000000
4  0.000000  0.000000  1.581139  0.000000  1.581139  1.118034  0.000000
5  1.581139  0.000000  0.000000  0.000000  1.581139  1.118034  0.000000
6  0.000000  2.236068  0.000000  0.000000  1.581139  1.118034  0.000000
7  1.581139  0.000000  0.000000  1.290994  0.000000  0.000000  2.236068
8  1.581139  0.000000  0.000000  0.000000  1.581139  1.118034  0.000000
9  1.581139  0.000000  0.000000  1.290994  0.000000  0.000000  2.236068

In [98]:
Z = pd.concat([Z1_standarized, Z2], axis=1).round(3)

In [99]:
Z

puissance  longueur  hauteur  poids    CO2  Autres  Europe  France  Diesel  \
0     -1.103    -0.614   -0.419 -0.989 -1.127   0.000   2.236   0.000   1.291   
1     -0.304    -0.485   -0.733 -0.411 -1.148   0.000   0.000   1.581   1.291   
2      0.532     1.192   -0.838  0.795  0.558   0.000   0.000   1.581   1.291   
3     -0.152     1.063    0.524  0.837 -0.179   0.000   0.000   1.581   1.291   
4     -1.280    -2.007   -0.628 -1.993 -1.169   0.000   0.000   1.581   0.000   
5      2.256     1.476   -0.524  1.189  1.990   1.581   0.000   0.000   0.000   
6     -0.761    -0.614   -1.047 -1.031 -0.600   0.000   2.236   0.000   0.000   
7      0.507     0.263    1.466  0.344  0.853   1.581   0.000   0.000   1.291   
8      0.773    -0.408    0.105  0.344  0.811   1.581   0.000   0.000   0.000   
9     -0.469     0.134    2.094  0.915  0.011   1.581   0.000   0.000   1.291   

   Essence    non    oui  
0    0.000  1.118  0.000  
1    0.000  1.118  0.000  
2    0.000  1.118  0.000  
3    0.000  1.118  0.000  
4    1.581  1.118  0.000  
5    1.581  1.118  0.000  
6    1.581  1.118  0.000  
7    0.000  0.000  2.236  
8    1.581  1.118  0.000  
9    0.000  0.000  2.236

# Analysis AFDM

In [100]:
from fanalysis.pca  import PCA

afdm = PCA(std_unit=False, row_labels=dataOriginal.index, col_labels=[Z1.columns, Z2.columns])
afdm.fit(Z)
#afdm.fit(Z)

AttributeError: 'Series' object has no attribute 'reshape'

In [76]:
from prince import FAMD

afdm = FAMD(n_components =3, n_iter = 3, random_state = 101) #FAMD(std_unit=False, row_labels=dataOriginal.index, col_labels=[Z1.columns, Z2.columns])
afdm.fit(dataOriginal[v_quantitative + v_qualitative])
#afdm.fit(Z)

FAMD(check_input=True, copy=True, engine='auto', n_components=3, n_iter=3,
     random_state=101)

In [77]:
afdm.explained_inertia_

array([0.41612849, 0.25007996, 0.19260293])

In [78]:
correlation_matrix = np.corrcoef(Z.transpose())

pd.DataFrame(correlation_matrix.round(4), columns = Z.columns, index = Z.columns)
eig_vals, eig_vecs = np.linalg.eig(correlation_matrix)

In [84]:
eig_vals.round(3)

array([ 5.097e+00,  3.097e+00,  2.248e+00,  1.124e+00,  1.980e-01,
        1.810e-01,  3.700e-02,  1.600e-02,  2.000e-03, -0.000e+00,
       -0.000e+00,  0.000e+00])

In [67]:
eig_vecs

array([[ 2.86217886e-01,  3.95592369e-01, -1.54428853e-01,
        -3.79709645e-02, -3.88986974e-01, -2.00101437e-01,
         8.39199022e-03,  5.47676728e-01,  4.94898232e-01,
         2.31969933e-14, -2.18162500e-14, -5.49421001e-31],
       [ 2.93455070e-01,  1.54522334e-01, -3.84807585e-01,
        -3.21804844e-01,  1.30635617e-01,  4.18527446e-01,
        -2.61548104e-02,  3.58834693e-01, -5.62756107e-01,
        -2.66496333e-14,  2.25726434e-14,  2.57244484e-17],
       [ 3.39031868e-01, -2.80684450e-01,  1.70061837e-01,
         1.37917947e-01,  6.07949152e-01, -1.29167908e-02,
        -4.90743854e-01,  2.94667453e-01,  2.46786935e-01,
         1.07023812e-14, -1.02708658e-14, -7.34781494e-17],
       [ 3.75985943e-01,  1.16516184e-01, -2.72348770e-01,
        -1.29660869e-01,  4.37059449e-01,  2.04854204e-02,
         5.55268203e-01, -3.68309893e-01,  3.44466527e-01,
         1.63683884e-14, -1.35073945e-14,  3.40455835e-17],
       [ 3.39083643e-01,  3.48203371e-01, -3.5776772

# Numero de facteurs a retenir

6. Faites une analyse du nombre de facteurs principaux à retenir. Justifiez votre raisonnement et les différentes étapes à 
réaliser

In [18]:
p = Z.shape[1] # All
p2 = len(v_qualitative) # Z2.shape[1] # Cualitatives
Fmax = p - p2  # numero de variables quantitatives es el max numero de valores propios
Fmax

9

In [19]:
p #No columnes of Z (normalised multitype)

12

In [20]:
p2 # No. variables qualitatives

3

In [21]:
print('Le numero maximo de facteur principaux est: ', Fmax)

Le numero maximo de facteur principaux est:  9


# 7. Déterminez les valeurs propres de l’ensemble des données

In [32]:
dfVPropes = pd.DataFrame(afdm.erg_)

AttributeError: 'FAMD' object has no attribute 'erg_'

In [23]:
# 8. Déterminez la contribution des variables aux 2 premiers axes factoriels. Commentez les résultats.

In [ ]:
# 9. Représentez graphiquement les variables et les individus sur le même graphique.